### ISSUE TITLE
Support for identity.name

### ISSUE THREAD

**Issue by crisrat** [tradablebits/livekit-server-sdk-python#1]
Hi and thanks for making this
I'm using it and works fine for me
Wanted to ask if I'm missing something or this feature isn't supported:

When you create a token, along with the identity and other stuff, you can also give that user a name (in the participant info)
https://docs.livekit.io/server/room-management/#participantinfo

That name is used in the front-end
```displayName = participant.name || participant.identity;```
But I don't see anywhere in this package the `name`
For example, this php package seems to have it
`https://github.com/agence104/livekit-server-sdk-php/blob/f6965a4d593356ffa762648c4acbb2cbfe048251/src/AccessToken.php#L89`
I presume it's a new feature of livekit, perhaps

**Comment by crisrat** [comment]
> Looks like the participant name was added in v0.15.2: https://github.com/livekit/livekit/releases/tag/v0.15.2
> 
> I'll update to the latest livekit version soon!

thanks for your quick reply
that would be awesome, thank you :)

**Comment by AlexJMohr** [comment]
@crisrat Just released v0.4.0. Let me know if it works for you.

**Comment by crisrat** [comment]
Already in use
Works as expected
Thank you so much
