### ISSUE TITLE
Connect to room and listen for data events

### ISSUE THREAD

**Issue by cristianrat** [tradablebits/livekit-server-sdk-python#4]
Hi @AlexJMohr 
I'm wondering how (if at all possible) I could connect to a room from the backend, and listen to data events. 
At the moment the only webhooks livekit supports are on participant leave etc, but not on data messages, I was looking at that option
Not having that ability is quite limiting, as I can send WS data, but cannot receive (meaning I have to receive API calls instead)
I've been using the channels py library as well, but don't want to use two WS systems - so want to get rid of that one entirely

**Comment by AlexJMohr** [comment]
Hi @cristianrat 

It sounds like that is client functionality, so wouldn't be a good fit for this library, which is a server-side SDK. This library is meant to mirror the functionality of the official livekit server SDKs like [server-sdk-js](https://github.com/livekit/server-sdk-js). If that's something that the official server SDKs support, then we should too.

**Comment by cristianrat** [comment]
Thanks for the quick reply @AlexJMohr 
Yeah, kinda thought so as well :)
