### ISSUE TITLE
How to use this SDK for egress server

### ISSUE THREAD

**Issue by nhha1602** [tradablebits/livekit-server-sdk-python#5]
Hi,

I want to use this SDK and with gstreamer for python to do an egress server - called "myegress".

My scenario is:
- When we send TrackCompositeEgressRequest to livekit server
- livekit server will send media stream to "myegress"
- at "myegress" will receive this media stream and I will captured it by OpenCV.
- And then I will apply AI model detection for captured images

Please advise if I can use this SDK for above scenario?

**Comment by AlexJMohr** [comment]
You should be able to use this SDK to send a `TrackCompositeEgressRequest`. In your case it sounds like you want to livekit to output an [RTMP Stream](https://docs.livekit.io/server/egress/#streamoutput). I believe you want the `livekit.twirp.livekit_egress_twirp` module from this library. To be honest I don't know if it's the Client or the Server (this code is generated from the livekit proto files)

The receiver of the stream would likely be a separate process where you would capture it with gstreamer and do your post-processing.

**Comment by nhha1602** [comment]
Thank you for your answers. I tried with TrackCompositeEgressRequest and output is RTMP stream. Then I used OpenCV read the RTMP setram. But I got a delay from input stream to output stream ~ 25 seconds (I expected a deplay < 3 seconds). I'm not sure it cause by RTMP stream or cause by OpenCV.
My flow as below: 

A client send request: TrackCompositeEgressRequest to livekit-server
Egress extract video and connect to a RTMP server.
The client connect to RTMP server using OpenCV and read RTMP stream
At the client side, I saw that the RTMP stream was deplayed about 25 seconds.

That why, I tried to use another solution - write an egress by using this SDK, so that I dont need to use RTMP. Because, Egress use gstreamer, so I can capture video at egress end point using OpenCV (OpenCV support gstreamer).

Please advise.

Thanks and regards,

**Comment by AlexJMohr** [comment]
Apologies for the delayed response. Unfortunately I'm not able to provide support with this one. I suggest trying to mock up what you want to do using one of the official server SDKs: https://docs.livekit.io/references/server-sdks/ or ask for help through the official livekit channels.
