### ISSUE TITLE
Basic Instructions as developer - Windows

### ISSUE THREAD

**Issue by majidkhn** [tradablebits/livekit-server-sdk-python#6]
Can i get basic instructions on how to setup my development env on pycharm and how to i start the server. 

i ran the following
i created development.env file and added export LIVEKIT_API_KEY=<MYKEY>
export LIVEKIT_API_SECRET=<MYSecret>
git clone --recurse-submodules https://github.com/tradablebits/livekit-server-sdk-python.git
python3 -m venv env
source env/Script/activate
pip install --editable .  // . is for current folder

i am not sure how do i proceed further, can you guide me on how to start the server, 

I also have GoLang installed on my system

It will be great help if you could guide me further. Thanks

**Comment by AlexJMohr** [comment]
Apologies for the delayed response. I'm not sure what you're trying to do here. Are you trying to make changes to this library locally, or are you trying to use the library in your own project? If you're trying to make changes to this library, there is no server to run other than one you write yourself for testing purposes.

**Comment by majidkhn** [comment]
Thanks for Reply @AlexJMohr , initially when i saw i got confused. actually i am trying to use your sdk, i was able to create token and create room. etch. however i couldn't connect to room. i was wondering if this library supports all the functionality livekit provides. like roomcallback etc.

**Comment by majidkhn** [comment]
it would be very helpful if you could forward me to few of the examples or implementation of this library.

**Comment by AlexJMohr** [comment]
This library is just python bindings to the livekit RPC protocol (https://github.com/livekit/protocol), so the library can do anything defined in the protocol. The official livekit examples should translate fairly well to this library.
